# Generated by Django 5.2 on 2025-04-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='corridor',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
